### ISSUE TITLE
Generate a base interface for repositories as part of the templates....

### ISSUE THREAD

**Issue by natiki** [aspnetboilerplate/aspnetboilerplate-templates#70]
Hi,

Currently the templates generate the following class assuming an application name of TreasurePlatform

```c#
public abstract class TreasurePlatformRepositoryBase<TEntity, TPrimaryKey> : EfRepositoryBase<TreasurePlatformDbContext, TEntity, TPrimaryKey>
        where TEntity : class, IEntity<TPrimaryKey>
```

and if I have it right then a repository interface is declared as:

```c#
public interface ITpDboPlatformUsersRepository : IRepository<PlatformUserTableModel, long>
```

however the issue arises that if you want to implement custom methods for all your repositories *and* you are resolving them via IoC then you would have to cast them back to TreasurePlatformRepositoryBase to get at any new methods added.

Instead I suggest generating a base interface for repositories as follows:

```c#
 /// <summary>
 ///     Contract that all repositories need to honour within the application.
 /// </summary>
public interface ITreasurePlatformRepositoryBase<TEntity, TPrimaryKey> : IRepository<TEntity, TPrimaryKey> where TEntity : class,  IEntity<TPrimaryKey>
{
    //Example of new method that is available to all repositories    
    //TEntity GetOrDefault(TPrimaryKey aId);
}
```

So if I added the extra method GetOrDefault() in TreasurePlatformRepositoryBase I would be done and I can now resolve ITpDboPlatformUsersRepository via IoC and get at the new method.

This would have made implementing #2448 easier as I did not have the base interface to start with.

**Comment by hikalkan** [comment]
You may use [AutoRepositoryTypes] attribute for your dbcontext. We consider to make this default in startup templates too.

**Comment by natiki** [comment]
Fair enough. However I am not sure I am in favour of "magical runtime descenants" generated for my repositories. How would I control the naming of them? How when looking at a code base can you see what is "actually there". How do you add functionality that is specific to only one repository?

**Comment by hikalkan** [comment]
> How do you add functionality that is specific to only one repository?

You can create custom repositories as described in the document: https://aspnetboilerplate.com/Pages/Documents/EntityFramework-Integration#DocCustomRepositoryMethods

**Comment by natiki** [comment]
I understand the creation of custom repositories but then this is mutually exclusive to using "AutoRepositoryTypes"?

**Comment by hikalkan** [comment]
If you create a PersonRepository (and corresponding IPersonRepository) then you can directly inject IPersonRepository and use as you like. You can access to custom methods on IPersonRepository.

AutoRepositoryTypes is used to define type of repository class used by default when you inject ``IRepository<T>`` (if you used it, you can define another interface too).

If you expect that you add a custom method to your custom repository than access that method through ``IRepository<T>`` reference, as you know it's impossible because of C# basics. However you can add extension methods to ``IRepository<T>`` as I instantiated here: https://gist.github.com/hikalkan/74f624c0b42c78fb1619e92b3d1972f8

Every structure has it's own benefits and you can combine them to implement your requirements.
